# --- Sitio ---
title: "Libro de Biología Celular y Molecular — UNSAAC"
remote_theme: pmarsceill/just-the-docs
description: "Libro digital, abierto y en evolución del curso de Biología Celular y Molecular (UNSAAC)."
lang: es-PE

# Back to top link
back_to_top: true
back_to_top_text: "Regresar al inicio"

footer_content: "Repositorio mantenido por Francisco Ascue y Estudiantes<a href=\"https://github.com/FranciscoAscue\">GitHub</a>"

#color_scheme: "dark"
logo: "/img/logo.webp"
